### ISSUE TITLE
Service Rewrite Epic

### ISSUE THREAD

**Issue by manio143** [iqasport/referee_hub#351]
Deadline April 2023

## Motivation
The service needs to be upgraded. It's running on a ruby stack that is no longer supported. The fronted app is served using rails webpacker, which is deprecated.

There are two choices, upgrade the app to use latest ruby and rails, or rewrite it. Unfortunately I don't feel comfortable enough with ruby to upgrade the service with confidence and fix all the breaks. I didn't want to do a rewrite but I feel it's necessary. I researched that it can still be hosted on Heroku using a docker container.

## Work tracking
I'm the most familiar with .NET as that's what I use at work. ASP.NET should be a good replacement for rails, with EntityFramework Core as the database ORM.

But first I need to write tests against the existing service such that when doing the rewrite I can maintain a high degree of compatibility. This way I will also be able to highlight any hidden bugs.
See https://github.com/iqasport/referee_hub/tree/feature/dotnet-system-test

- [ ] API tests of the existing service
- [ ] New service creation, CI, deployment
- [ ] Moving some APIs over for a percentage of users
- [ ] All APIs are moved to the new service
- [ ] UX is made standalone and calls into the new API
- [ ] Old service is shut down
